# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2509a1f9876d446dd6163bc9500935e38e51df4cd3f2abd6bc521c1e5d89351368b3d728e956ceb16cfa3f527cef72a66086e52c86a6712d0b8a412627ca6b8

test:
  secret_key_base: 699d4da95fec7e4fea703af793d1ffa54cd00a18c8ca259b58300164cb2b13c03d558c3771d3ee7623ad7b25bed43db6de8186ec2166a154e188c61bbef45f0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
